### ISSUE TITLE
NOAA Notebook Improvements

### ISSUE THREAD

**Issue by siddharth0248** [US-GHG-Center/ghgc-docs#106]
**Description:**

We need to improve our [existing NOAA notebook](https://us-ghg-center.github.io/ghgc-docs/user_data_notebooks/noaa-insitu_User_Notebook.html) to enhance its functionality and user experience. 

[NOAA Greenhouse Gas Dataset](https://gml.noaa.gov/aftp/data/greenhouse_gases/) available in netCDF and text
[Near Real Time Data](https://gml.noaa.gov/ccgg/trends/mlo.html)

The improvements should focus on the following areas:
1. **Data Source:** Modify the notebook to read data directly from the NOAA website instead of reading files from Git Hub.
   
2. **Near Real-Time Data (NRT):** Incorporate the capability to handle near real-time (NRT) data, allowing users to analyze the most current data available.

3. **Comparison of Stations:** Add functionality to compare data from two different stations. This feature will enable users to perform comparative analyses between different geographical locations or time periods.

4. **Interactive Plots:** Implement interactive plots to make data visualization more dynamic and user-friendly. This will allow users to explore the data more effectively. [e.g](https://gml.noaa.gov/ccgg/trends/graph.html)

**Success Criteria:**

- [ ] The notebook successfully reads data from the NOAA website
- [ ] Near real-time (NRT) data handling is implemented and functioning correctly.
- [ ] Users can select and compare data from two different stations within the notebook.
- [ ] Interactive plots are integrated and provide a seamless user experience.

**Comment by Jeanne-le-Roux** [comment]
Next steps:
- Review the updates (will present to HQ tomorrow)
- Decide what to integrate into GHGC Docs
