### ISSUE TITLE
GOES labeled plumes transformation and ingestion

### ISSUE THREAD

**Issue by paridhi-parajuli** [US-GHG-Center/ghgc-docs#139]
- [x] Reproject
- [x] Apply masking
- [x] Reingest

**Comment by siddharth0248** [comment]
We received the new dataset, which includes the following:  
- CH4_Enhancement  
- CH4_plume_mask  

@paridhi-parajuli - masking the CH4 enhancement layer using the plume mask. This will ensure that only the pixels corresponding to the plume are included, improving the visualization.  

Once done, we will share the initial files with @sanzog03 for visualizing the animation.

**Comment by Jeanne-le-Roux** [comment]
Waiting for updated CH4_plume_mask files from Daniel & Tailong (to match the existing data and not the new CH4_Enhancement they shared last week).
