### ISSUE TITLE
Customize organization and content of the docs website

### ISSUE THREAD

**Issue by slesaad** [US-GHG-Center/ghgc-docs#2]
# PI Objective
...

# Description
Now that we've set up the website to host the notebooks at https://us-ghg-center.github.io/ghgc-docs/, we need to better organize the content of the website.

See example of veda-docs https://nasa-impact.github.io/veda-docs/, repo here: https://github.com/NASA-IMPACT/veda-docs

# Acceptance Criteria
- [ ] The docs website has relevant content organized in a user-friendly manner

**Comment by slesaad** [comment]
I have added some files/templates for PDF and code rendering and some organization:

1. Each section links to a `<section>/index.qmd` file, this file should contain what the section means and the table of contents - example here: https://github.com/US-GHG-Center/ghgc-docs/blob/main/cog_transformation/index.qmd
2. For processing and verification report, each dataset will have a `qmd` file and within it, the corresponding pdf will be embedded - example here: https://github.com/US-GHG-Center/ghgc-docs/blob/main/processing_and_verification_reports/casagfed-carbonflux-monthgrid-v3_Processing%20and%20Verification%20Report.qmd
3. Similar for cog transformation scripts and data workflows, example: https://github.com/US-GHG-Center/ghgc-docs/blob/main/cog_transformation/casagfed-carbonflux-monthgrid-v3_Transformation_Code.qmd and https://github.com/US-GHG-Center/ghgc-docs/blob/main/data_workflow/casagfed-carbonflux-monthgrid-v3_Data_Flow.qmd

Caveats: For the data transformation scripts - we maintain two copies: one as `.py` file and another in the `.qmd` for rendering purposes - will need to be careful about keeping each up-to-date. Any other ideas are welcome.

@siddharth0248 can you add files and content based on what I described above?

Tagging @j08lue too since you offered help 😄

**Comment by j08lue** [comment]
> For the data transformation scripts - we maintain two copies: one as `.py` file and another in the `.qmd` for rendering purposes - will need to be careful about keeping each up-to-date. Any other ideas are welcome.

I think we should convert these `.py` scripts to notebooks. Then they are executable and render nicely at the same time.

**Comment by slesaad** [comment]
agreed!
