### ISSUE TITLE
Renaming the STAC collection

### ISSUE THREAD

**Issue by SwordSaintLancelot** [US-GHG-Center/ghgc-docs#23]
The STAC collection in the production environment are to be renamed.

## Acceptance Criteria

- [x] rename ceos-co2budget-yeargrid-v1 to oco2-based-co2budget-yeargrid-v1
- [x] rename ceos-meanco2budget-yeargrid-v1 to oco2-based-meanco2budget-yeargrid-v1

**Comment by j08lue** [comment]
```bash
find . -type f -name "*.ipynb" -exec sed -i '' 's/ceos-co2budget-yeargrid-v1/oco2-based-co2budget-yeargrid-v1/g' {} \;
```

**Comment by j08lue** [comment]
Looks like this was done in https://github.com/US-GHG-Center/ghgc-docs/pull/21?

**Comment by SwordSaintLancelot** [comment]
The names had been changed multiple times so I think this might have been changed before we put it into the production environment because I can see the old STAC names in the prod environment.
