### ISSUE TITLE
Include a link to the dataset landing pages in each notebook

### ISSUE THREAD

**Issue by j08lue** [US-GHG-Center/ghgc-docs#24]
from @deborahUAH:

## Acceptance criteria

- [x] included a link to the dataset landing pages in each notebook

**Comment by SwordSaintLancelot** [comment]
@j08lue Do we need to just add the links to the data cards in the notebooks? If so, Shouldn't this be done after the earth.gov platform is finalized?

**Comment by j08lue** [comment]
> If so, Shouldn't this be done after the earth.gov platform is finalized?

Yes, good call. Let's wait until the URL is more stable.
